#!/bin/bash
# usage: ./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>
# usage: ./runCDN -p 20520 -o cs5700cdnorigin.ccs.neu.edu -n cdn-dns.khoury.northeastern.edu -u gupta.uj -i ssh-ed25519-gupta.uj.priv 

# ssh -v -i ${10} $8@cdn-dns.khoury.northeastern.edu "kill -9 \$(lsof -t -i:$2); ./dnsserver -p $2 -n $6"

# ssh -v -i ${10} $8@cdn-http3.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")
# ssh -v -i ${10} $8@cdn-http4.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")
# ssh -v -i ${10} $8@cdn-http7.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")
# ssh -v -i ${10} $8@cdn-http11.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")
# ssh -v -i ${10} $8@cdn-http14.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")
# ssh -v -i ${10} $8@cdn-http15.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")
# ssh -v -i ${10} $8@cdn-http16.khoury.northeastern.edu 'bash -s' < <(echo "kill -9 $(lsof -t -i:$2); ./httpserver -p $2 -o $4")

# ssh -v -i ${10} $8@cdn-http3.khoury.northeastern.edu "./httpserver -p $2 -o $4 "
# ssh -v -i ${10} $8@cdn-http4.khoury.northeastern.edu "./httpserver -p $2 -o $4 "
# ssh -v -i ${10} $8@cdn-http7.khoury.northeastern.edu "./httpserver -p $2 -o $4 "
# ssh -v -i ${10} $8@cdn-http11.khoury.northeastern.edu "./httpserver -p $2 -o $4 "
# ssh -v -i ${10} $8@cdn-http14.khoury.northeastern.edu "./httpserver -p $2 -o $4 "
# ssh -v -i ${10} $8@cdn-http15.khoury.northeastern.edu "./httpserver -p $2 -o $4 "
# ssh -v -i ${10} $8@cdn-http16.khoury.northeastern.edu "./httpserver -p $2 -o $4 "


# use nohup and & to run a program in the background and have it survive ssh log-out

# ssh -v -i ${10} $8@cdn-dns.khoury.northeastern.edu "nohup ./dnsserver -p $2 -n $6 &"

# ssh -v -i ${10} $8@cdn-http3.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"
# ssh -v -i ${10} $8@cdn-http4.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"
# ssh -v -i ${10} $8@cdn-http7.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"
# ssh -v -i ${10} $8@cdn-http11.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"
# ssh -v -i ${10} $8@cdn-http14.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"
# ssh -v -i ${10} $8@cdn-http15.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"
# ssh -v -i ${10} $8@cdn-http16.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 & exit"

#-------------------

#nohup ./httpserver -p 20521 -o cs5700cdnorigin.ccs.neu.edu > /dev/null 2>&1 &

# nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 &

ssh -v -i ${10} $8@cdn-http3.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"
ssh -v -i ${10} $8@cdn-http4.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"
ssh -v -i ${10} $8@cdn-http7.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"
ssh -v -i ${10} $8@cdn-http11.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"
ssh -v -i ${10} $8@cdn-http14.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"
ssh -v -i ${10} $8@cdn-http15.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"
ssh -v -i ${10} $8@cdn-http16.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 > /dev/null 2>&1 & exit"

# ------------------


# ssh -v -i ${10} $8@cdn-dns.khoury.northeastern.edu "nohup ./dnsserver -p $2 -n $6 &"

# ssh -v -i ${10} $8@cdn-http3.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"
# ssh -v -i ${10} $8@cdn-http4.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"
# ssh -v -i ${10} $8@cdn-http7.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"
# ssh -v -i ${10} $8@cdn-http11.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"
# ssh -v -i ${10} $8@cdn-http14.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"
# ssh -v -i ${10} $8@cdn-http15.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"
# ssh -v -i ${10} $8@cdn-http16.khoury.northeastern.edu "nohup ./httpserver -p $2 -o $4 &"