#!/bin/bash
# usage: ./stopCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>
# usage: ./stopCDN -p 20520 -o cs5700cdnorigin.ccs.neu.edu -n cdn-dns.khoury.northeastern.edu -u gupta.uj -i ssh-ed25519-gupta.uj.priv 

ssh -i ${10} $8@cdn-dns.khoury.northeastern.edu "killall -u $8 python3; exit"

ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "killall -u $8 python3; exit"
ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "killall -u $8 python3; exit"
ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "killall -u $8 python3; exit"
ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "killall -u $8 python3; exit"
ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "killall -u $8 python3; exit"
ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "killall -u $8 python3; exit"

# ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "pkill -f httpserver; exit"
# ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "pkill -f httpserver; exit"
# ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "pkill -f httpserver; exit"
# ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "pkill -f httpserver; exit"
# ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "pkill -f httpserver; exit"
# ssh -i ${10} $8@cdn-http3.khoury.northeastern.edu "pkill -f httpserver; exit"