#!/usr/bin/env python3

import argparse
import socket
from dnslib import *

HOST = 'cdn-dns.khoury.northeastern.edu'
PORT = 20500
ORIGIN_SERVER = 'cdn-origin.khoury.northeastern.edu'
# QUERY_DOMAIN = 'cs5700cdn.example.com.'
REPLICA_SIZE = 7
REPLICA_SERVERS = [
    "cdn-http3.khoury.northeastern.edu", 
    "cdn-http4.khoury.northeastern.edu", 
    "cdn-http7.khoury.northeastern.edu", 
    "cdn-http11.khoury.northeastern.edu", 
    "cdn-http14.khoury.northeastern.edu", 
    "cdn-http15.khoury.northeastern.edu", 
    "cdn-http16.khoury.northeastern.edu"
]

class DNSServer:
    def __init__(self, host=HOST, port=PORT):
        self.host = host
        self.port = port
        self.i = 0 # index for replica servers for round-robin

    def run(self):
        # set up a socket with context manager, so s will be closed when interrupted
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s: # DNS uses UDP
            # s.bind((self.host, self.port))
            s.bind(('0.0.0.0', self.port)) # bind to all interfaces
            print(f'Server listening on {self.host}:{self.port}')
            # listen for requests
            while True:
                data, addr = s.recvfrom(1024)
                print("\nReceived request from", addr)
                try:
                    # parse/handle the request
                    self.handle_request(data, addr)
                except Exception as e:
                    print("Error handling request:", e)
                    continue

    def handle_request(self, data, addr):
        '''parse the request, resolve qname, and send response'''
        request = DNSRecord.parse(data)
        print("Parsed Request:\n", request)
        # check type == A: if false, dismiss
        if request.q.qtype != QTYPE.A:
            print("Request type is not A")
            return
        # send response
        self.send_response(request, addr)
    
    def send_response(self, request, client_addr):
        '''construct and send packed response back to client'''
        # resolve the requested domain 
        res_ip = self.get_server_ip(client_addr[0], request.q.qname)
        # construct the response
        # dns_res = DNSRecord(DNSHeader(id=request.header.id, qr=1, aa=1, ra=1), q=request.q)
        dns_res = request.reply() # a reply skeleton with id, flags, and question section filled
        dns_res.add_answer(RR(request.q.qname, QTYPE.A, rdata=A(res_ip), ttl=60))
        print("Response to send:\n", dns_res)
        # send the response
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as reply_socket:
            reply_socket.sendto(dns_res.pack(), client_addr)
            print("Response sent to", client_addr)


    def get_server_ip(self, client_ip, qname):
        '''use round-robin for now to return one of the replica servers' IP address'''
        # looks like the requested domain is alway the same (from simulation only, actual test may vary)
        requested_domain = qname # for now; TODO: parse the requested domain and check if it's our ORIGIN_SERVER
        #TODO: use active measurement (maybe scamper) to find the best replica ip, 
        #TODO: can add cache to store the best replica ip for each client as well
        replica_server = REPLICA_SERVERS[self.i]
        replica_ip = socket.gethostbyname(replica_server)
        self.i = (self.i + 1) % REPLICA_SIZE
        return replica_ip


# to copy the file to the server from local machine: 
# scp -v -i priv_key_path file_to_copy username@cdn-dns.khoury.northeastern.edu:

# to run the server on the server machine:
# ssh into the server machine and run this program

# to test our dns server, use dig in terminal:
# dig @cdn-dns.khoury.northeastern.edu -p [port] cs5700cdn.example.com

def main():
    # usage: $ ./dnsserver [-p port] [-n name]
    parser = argparse.ArgumentParser(description='DNS Server')
    parser.add_argument('-p', type=int, help='port number', default=PORT)
    parser.add_argument('-n', type=str, help='name', default=HOST)
    args = parser.parse_args()

    server = DNSServer(args.n, args.p)
    server.run()

if __name__ == '__main__':
    main()
                